// Generates src/components/icon-paths.ts from the SVGs in design/icons.
// Run `npm run icons` after the designer updates an icon.
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = new URL('..', import.meta.url).pathname
const entries = []
for (const group of ['category', 'ui']) {
  const dir = join(root, 'design/icons', group)
  for (const file of readdirSync(dir)
    .filter((f) => f.endsWith('.svg'))
    .sort()) {
    const svg = readFileSync(join(dir, file), 'utf8').trim()
    const inner = svg
      .replace(/^<svg[^>]*>/, '')
      .replace(/<\/svg>$/, '')
      .trim()
    entries.push([file.replace(/\.svg$/, ''), inner])
  }
}

const out = `// Generated by scripts/gen-icons.mjs from design/icons. Do not edit by hand.
export const iconPaths = {
${entries.map(([name, inner]) => `  ${JSON.stringify(name)}: ${JSON.stringify(inner)},`).join('\n')}
} as const

export type IconName = keyof typeof iconPaths
`
writeFileSync(join(root, 'src/components/icon-paths.ts'), out)
console.log(`Wrote ${entries.length} icons`)
