// Generates src/data/thailand.generated.ts (all provinces and districts).
//
// Source: the "province" npm package (MIT), which follows DOPA/Thai Post data.
// Run with:  npm i --no-save province && node scripts/gen-areas.mjs
//
// Slugs are built from the English names. Slugs that were already live are
// pinned in LEGACY so stored places and shared links keep working.
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import rows from 'province/dist/provinces.js'

const root = new URL('..', import.meta.url).pathname

// Wrong or inconsistent English names in the source data (keyed by Thai).
const EN_FIX = {
  'ลพบุรี|': 'Lop Buri',
  'ลพบุรี|เมืองลพบุรี': 'Mueang Lop Buri',
  'บุรีรัมย์|โนนสุวรรณ': 'Non Suwan',
  'อุดรธานี|หนองหาน': 'Nong Han',
  'มุกดาหาร|ดงหลวง': 'Dong Luang',
  'แพร่|ร้องกวาง': 'Rong Kwang',
  'สุราษฎร์ธานี|วิภาวดี': 'Wiphawadi',
  'สุราษฎร์ธานี|เกาะพะงัน': 'Ko Pha-ngan',
  'นราธิวาส|บาเจาะ': 'Bacho',
  'พังงา|': 'Phang Nga',
}

// Shorter display names.
const TH_SHORT = { กรุงเทพมหานคร: 'กรุงเทพฯ' }

// Slugs already in use before this file existed.
const LEGACY_PROVINCE = { กรุงเทพมหานคร: 'bangkok', ชลบุรี: 'chonburi' }
const LEGACY_DISTRICT = {
  'กรุงเทพมหานคร|ป้อมปราบศัตรูพ่าย': 'pom-prap-sattru-phai',
  'กรุงเทพมหานคร|ยานนาวา': 'yan-nawa',
  'กรุงเทพมหานคร|บึงกุ่ม': 'bueng-kum',
  'กรุงเทพมหานคร|บางซื่อ': 'bang-sue',
  'กรุงเทพมหานคร|ราชเทวี': 'ratchathewi',
  'กรุงเทพมหานคร|คันนายาว': 'khan-na-yao',
  'กรุงเทพมหานคร|วังทองหลาง': 'wang-thonglang',
  'กรุงเทพมหานคร|ทุ่งครุ': 'thung-khru',
  'ชลบุรี|เมืองชลบุรี': 'mueang-chonburi',
}

const slugify = (s) =>
  s
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')

const provinces = new Map()
for (const r of rows) {
  const pth = r.city_th
  if (!provinces.has(pth)) {
    const en = EN_FIX[`${pth}|`] ?? r.city
    provinces.set(pth, { th: pth, en, districts: new Map() })
  }
  const p = provinces.get(pth)
  if (!p.districts.has(r.district_th)) {
    p.districts.set(r.district_th, EN_FIX[`${pth}|${r.district_th}`] ?? r.district)
  }
}

const thai = new Intl.Collator('th')
const out = [...provinces.values()]
  .map((p) => {
    const used = new Set()
    const districts = [...p.districts]
      .map(([th, en]) => {
        let slug = LEGACY_DISTRICT[`${p.th}|${th}`] ?? slugify(en)
        for (let i = 2; used.has(slug); i++) slug = `${slugify(en)}-${i}`
        used.add(slug)
        return { slug, name: th }
      })
      .sort((a, b) => thai.compare(a.name, b.name))
    return { slug: LEGACY_PROVINCE[p.th] ?? slugify(p.en), name: TH_SHORT[p.th] ?? p.th, districts }
  })
  .sort((a, b) => (a.slug === 'bangkok' ? -1 : b.slug === 'bangkok' ? 1 : thai.compare(a.name, b.name)))

const provinceSlugs = new Set(out.map((p) => p.slug))
if (provinceSlugs.size !== out.length) throw new Error('duplicate province slug')

const body = out
  .map(
    (p) =>
      `  { slug: ${JSON.stringify(p.slug)}, name: ${JSON.stringify(p.name)}, districts: [\n` +
      p.districts
        .map((d) => `    { slug: ${JSON.stringify(d.slug)}, name: ${JSON.stringify(d.name)} },`)
        .join('\n') +
      `\n  ] },`,
  )
  .join('\n')

writeFileSync(
  join(root, 'src/data/thailand.generated.ts'),
  `// Generated by scripts/gen-areas.mjs. Do not edit by hand.
// ${out.length} provinces, ${out.reduce((n, p) => n + p.districts.length, 0)} districts.
import type { Province } from './areas'

export const thailand: Province[] = [
${body}
]
`,
)
console.log(`${out.length} provinces, ${out.reduce((n, p) => n + p.districts.length, 0)} districts`)
