import { thailand } from './thailand.generated'

// All 77 provinces and their districts, generated by scripts/gen-areas.mjs.
// Bangkok first, then Thai alphabetical order.
export type District = { slug: string; name: string }
export type Province = { slug: string; name: string; districts: District[] }

export const provinces: Province[] = thailand

/** Shown as quick-pick chips in the area picker; the rest are in a dropdown. */
export const popularProvinces = [
  'bangkok',
  'nonthaburi',
  'pathum-thani',
  'samut-prakan',
  'chiang-mai',
  'chonburi',
  'phuket',
]

export type Area = { province: Province; district?: District }

export function findArea(provinceSlug?: string, districtSlug?: string): Area | undefined {
  const province = provinces.find((p) => p.slug === provinceSlug)
  if (!province) return undefined
  if (!districtSlug) return { province }
  const district = province.districts.find((d) => d.slug === districtSlug)
  return district ? { province, district } : undefined
}

export function areaPath(area?: Area): string {
  if (!area) return ''
  return `/${area.province.slug}` + (area.district ? `/${area.district.slug}` : '')
}

/** Name of the most specific level, e.g. "ลาดกระบัง" or "กรุงเทพฯ". */
export function areaName(area: Area): string {
  return area.district?.name ?? area.province.name
}

export const AREA_COOKIE = 'area'

/** Cookie value is "province/district" or "province". */
export function parseAreaCookie(value?: string): Area | undefined {
  if (!value) return undefined
  const [p, d] = value.split('/')
  return findArea(p, d)
}
